#!/bin/bash
echo "Start postflight script"
VERSION_FOR_INSTALLER="2528";
URL="http://tw.rd.yahoo.com/referurl/keykey/client/installer/end/${VERSION_FOR_INSTALLER}M105/*http://tw.yimg.com/i/tw/download/ykkimg/blank.gif"
/usr/bin/curl -L -A "ChiakiKeyKey/2026.06 (macOS)" $URL  > /dev/null
# do not change lines below.
echo $SCRIPT_NAME: launching html help
open "/Library/Input Methods/Yahoo! KeyKey.app/Contents/SharedSupport/InstallerHelp.app"
echo "End postflight script"
exit 0
